#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

// hal_entry.c에 넣으면 정상동작
// 인터럽트를 이용해 LED1이 무한으로 blink되는 도중에, SW1를 누르면 LED2가 toggle됨.

/* Callback function */

int flag = 0;
void irq_callback(external_irq_callback_args_t *p_args)
{
    /* TODO: add your own code here */
    if(p_args->channel == 1){
        flag = !flag;
        R_IOPORT_PinWrite(&g_ioport_ctrl, LED2, flag);
    }
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    R_ICU_ExternalIrqEnable(&g_external_irq1_ctrl);

    while(1) {
        R_IOPORT_PinWrite(&g_ioport_ctrl, LED1, 1);
        R_BSP_SoftwareDelay(100, BSP_DELAY_UNITS_MILLISECONDS);
        R_IOPORT_PinWrite(&g_ioport_ctrl, LED1, 0);
        R_BSP_SoftwareDelay(100, BSP_DELAY_UNITS_MILLISECONDS);
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {

    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);
        R_ICU_ExternalIrqOpen(&g_external_irq1_ctrl, &g_external_irq1_cfg);


    }
}


