#include "hal_data.h"

// hal_entry.c에 넣으면 정상동작
// 버튼을 눌러 LED를 토글하는 코드

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

int isButton() {
    // 채터링 현상 해결을 위해 일정 시간 이상 눌려야 정상동작으로 인정
    bsp_io_level_t lev1, lev2;
    R_IOPORT_PinRead(&g_ioport_ctrl, SW1, &lev1);
    R_BSP_SoftwareDelay(100, BSP_DELAY_UNITS_MILLISECONDS);
    R_IOPORT_PinRead(&g_ioport_ctrl, SW1, &lev2);

    if (lev1==0 && lev2==0) return 0;
    return 1;
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    int flag = 0;
    while (1) {
        if (isButton() == 0) {
            flag++;
        }
        if (flag%2==0) {
            R_IOPORT_PinWrite(&g_ioport_ctrl, LED1, 1);
        }
        else {
            R_IOPORT_PinWrite(&g_ioport_ctrl, LED1, 0);
        }
    }

}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {

    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

    }
}

